version: '3.3'

services:

  web:
    image: movabletype:latest
    ports:
      - 80:80
    volumes:
      - ./data/mt-support:/var/www/html/mt-static/support
      - ./data/mt-config:/opt/mt-config
    restart: always

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql1234
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always

