version: '3.3'

services:

  web:
    image: yakumosaki/movabletype:latest
    ports:
      - 8080:80
    volumes:
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: mysql1234
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always

